services:
#    junior_etude.example:
#        class: Junior\EtudeBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    junior_etude.admin:
        class: Junior\EtudeBundle\Admin\EtudeAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Suivi d'étude"
              label: "Étude"
              label_catalogue: "JuniorEtudeBundle"
        arguments:
            - ~
            - Junior\EtudeBundle\Entity\Etude
            - ~

    junior_student.admin:
        class: Junior\EtudeBundle\Admin\StudentAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Suivi d'étude"
              label: "Étudiant"
              label_catalogue: "JuniorEtudeBundle"
        arguments:
            - ~
            - Junior\EtudeBundle\Entity\Student
            - ~

    junior_client.admin:
        class: Junior\EtudeBundle\Admin\ClientAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Suivi d'étude"
              label: "Client"
              label_catalogue: "JuniorEtudeBundle"
        arguments:
            - ~
            - Junior\EtudeBundle\Entity\Client
            - ~

    junior_company.admin:
        class: Junior\EtudeBundle\Admin\CompanyAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Suivi d'étude"
              label: "Entreprise"
              label_catalogue: "JuniorEtudeBundle"
        arguments:
            - ~
            - Junior\EtudeBundle\Entity\Company
            - ~