# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    sonata.user.registration.form.type:
        class: Application\Sonata\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }
        arguments:
            - "%fos_user.model.user.class%"
            - "%sonata.user.registration.form.options%"

    sonata.user.admin.user:
        class: Application\Sonata\UserBundle\Admin\Model\UserAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "sonata_user"
              label: "users"
              label_translator_strategy: "sonata.admin.label.strategy.underscore"
              label_catalogue: "SonataUserBundle"
              icon: "<i class='fa fa-users'></i>"
        arguments:
            - ~
            - Application\Sonata\UserBundle\Entity\User
            - "%sonata.user.admin.user.controller%"
        calls:
            - [ setUserManager, [ "@fos_user.user_manager" ]]
            - [ setTranslationDomain, [ "%sonata.user.admin.user.translation_domain%" ]]

    sonata.user.admin.rating:
        class: Application\Sonata\UserBundle\Admin\RatingAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "sonata_user"
              label: "Notation"
              label_catalogue: "SonataUserBundle"
              icon: "<i class='fa fa-users'></i>"
        arguments:
            - ~
            - Application\Sonata\UserBundle\Entity\Rating
            - ~

    sonata.user.admin.skill:
        class: Application\Sonata\UserBundle\Admin\SkillAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "sonata_user"
              label: "Compétence"
              label_catalogue: "SonataUserBundle"
              icon: "<i class='fa fa-users'></i>"
        arguments:
            - ~
            - Application\Sonata\UserBundle\Entity\Skill
            - ~